[package]
name = "algedi-provider-gdrive"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
algedi-provider-trait = { path = "../algedi-provider-trait" }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
oauth2 = { workspace = true }
tiny_http = { workspace = true }
tokio-util = { workspace = true }
